Models/SubjectAndHours.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TimeTable.Models
{
    public class SubjectAndHours
    {
        [Required]
        public string SubjectName { get; set; }
        [Required]
        public int SubjectTotalHours { get; set; }
        public int TotalHours { get; set; }
    }
}

Models/WorkingDays.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TimeTable.Models
{
    public class WorkingDays
    {
        [Required]
        [Range(1, 7, ErrorMessage = "Accepts only positive number between 1 to 7")]
        public int NoOfWorkingDays { get; set; }
        [Required]
        [Range(0, 8, ErrorMessage = "Accepts only positive number less than 9")]
       
        public int NoOfSubjectsPerDay { get; set; }
        [Required]
        public int TotalSubjects { get; set; }
    }
}

Controllers/GenerateTimeTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTable.Models;

namespace TimeTable.Controllers
{
    public class GenerateTimeTableController : Controller
    {
        // GET: GenerateTimeTable
        
        public ActionResult Index(int ? intTotalSubjects, int ? intTotalHoursForWeek)
        {
            ViewBag.TotalSubjects = intTotalSubjects;

            ViewBag.TotalHoursForWeek = intTotalHoursForWeek;
            return View();
        }
    }
}

Controllers/TimeTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTable.Models;

namespace TimeTable.Controllers
{
    public class TimeTableController : Controller
    {
        // GET: TimeTable
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(WorkingDays workingDays)
        {
            int intTotalHoursForWeek = 0, intTotalSubjects = 0;
            TempData["WorkingDays"] = workingDays.NoOfWorkingDays;
            TempData["SubjectsPerDay"] = workingDays.NoOfSubjectsPerDay;
            intTotalSubjects = workingDays.TotalSubjects;
            intTotalHoursForWeek = workingDays.NoOfWorkingDays * workingDays.NoOfSubjectsPerDay;
            return RedirectToAction("Index", "GenerateTimeTable", new
            {
                intTotalSubjects ,
                intTotalHoursForWeek,
            }) ; 
            
        }
    }
}

Views/GenerateTimeTable/Index.cshtml
@model TimeTable.Models.SubjectAndHours
@{
    ViewBag.Title = "Index";

    var varTotalSubjects = ViewBag.TotalSubjects;
    var varTotalHoursForWeek = ViewBag.TotalHoursForWeek;

}
<style type="text/css">
    /* Add CSS styling for the timetable */
    table {
        border-collapse: collapse;
        width: 100%;
        border: 2px solid #000; /* Add a border to the table */
    }

    th, td {
        border: 1px solid #000; /* Add a border to table headers and cells */
        text-align: center;
        padding: 10px;
    }
</style>


<form method="post" action="Index" id="frmTimetable">
    @if (ViewBag.TotalSubjects > 0)
    {
        <table>
            <thead>
                <tr>
                    <th>Subject Name</th>
                    <th>Total Hours</th>
                </tr>
            </thead>
            <tbody id="subjectFields">
                @for (var i = 0; i < ViewBag.TotalSubjects; i++)
                {
                    <tr>
                        <td>
                            @Html.TextBoxFor(m => Model.SubjectName, new { @class = "form-control", placeholder = "Subject Name", required = "required",  id = "txtSubjectName_" + i })
                        </td>
                        <td>
                            @Html.TextBoxFor(m => Model.SubjectTotalHours, new { @class = "form-control", placeholder = "Total Hours", onblur = "matchTotalHourse()", @type = "number", required = "required", id = "txtSubjectTotalHours_" + i })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    <br />
    <input type="hidden" id="hdnTotalSubjects" name="hdnTotalSubjects" value="@varTotalSubjects">
    <input type="hidden" id="hdnTotalHoursCount" name="hdnTotalHoursCount" value="@varTotalHoursForWeek" />
</form>

<div id="tableContainer">
    <input type="submit" name="submit" value="Generate" id="tblGenerateDynamicTimeTable" style="display:none"/>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        $("#tblGenerateDynamicTimeTable").click(function () {
            
                // Number of rows and columns
                var numRows = @TempData["WorkingDays"];
                var numCols = @TempData["SubjectsPerDay"];
                var hdnTotalHoursCount = $("#hdnTotalHoursCount").val();
                var strArrSubjectNames = [];

                for (var p = 0; p < parseInt(hdnTotalHoursCount); p++) {
                    var varSubjectName = $("#txtSubjectName_" + p).val();
                    var varSubjectTotalHours = $("#txtSubjectTotalHours_" + p).val();
                    for (var q = 0; q < parseInt(varSubjectTotalHours); q++) {
                        strArrSubjectNames.push(varSubjectName);
                    }
                }

                // Create a table element
                var table = $("<table></table>");
                // Create table body
                var tbody = $("<tbody></tbody>");
                var cellCounter = 0;

                for (var y = 0; y < numRows; y++) {
                    var row = $("<tr></tr>");
                    for (var z = 0; z < numCols; z++) {
                        if (cellCounter < strArrSubjectNames.length) {
                            row.append($("<td>" + strArrSubjectNames[cellCounter] + "</td>"));
                            cellCounter++;
                        } else {
                            row.append($("<td></td>"));
                        }
                    }
                    tbody.append(row);
                }
                table.append(tbody);

                $("#frmTimetable").hide();
                $("#tableContainer").html("");
                $("#tableContainer").append(table);
            
            });
    
    });

</script>
<script>
    function matchTotalHourse() {
        var varTotalHoursCount = 0, varTempTotalHoursCount = 0;
        varTempTotalHoursCount = $("#hdnTotalHoursCount").val()

        for (var m = 0; m < parseInt(varTempTotalHoursCount); m++) {
            var varSubjectTotalHours = $("#txtSubjectTotalHours_" + m).val();
            if (varSubjectTotalHours != undefined && varSubjectTotalHours != null && varSubjectTotalHours != "") {
                varTotalHoursCount += parseInt(varSubjectTotalHours);
            }

        }

        if (varTotalHoursCount != "" && varTempTotalHoursCount != undefined && varTempTotalHoursCount == varTotalHoursCount) {

            $("#tblGenerateDynamicTimeTable").show();
        }
        else {
            $("#tblGenerateDynamicTimeTable").hide();
        }
    }

</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dynamic Time-Table Generator</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dynamic Time-Table", "Index", "GenerateTimeTableController", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dynamic Time-Table Generator</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Views/TimeTable/Index.cshtml
@model TimeTable.Models.WorkingDays


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    @using (Html.BeginForm("Index", "TimeTable", FormMethod.Post))
                    {
                        <div class="form-group" style="padding:10px 0px 10px 0px">
                            <label>No. Of Working Days: </label><span style="color:red">*</span>
                            @Html.TextBoxFor(m => m.NoOfWorkingDays, new { @class = "form-control", @type = "number", @min = "1", @max = "7", required = "required", id = "txtNoOfWorkingDays" })
                        </div>
                        <div class="form-group" style="padding:10px 0px 10px 0px">
                            <label>No. Of Subjects Per Day: </label><span style="color:red">*</span>
                            @Html.TextBoxFor(m => m.NoOfSubjectsPerDay, new { @class = "form-control", @type = "number", @min = "0", @max = "8", required = "required", id = "txtNoOfSubjectPerDay" })
                        </div>
                        <div class="form-group" style="padding:10px 0px 10px 0px">
                            <label>Total Subject: </label><span style="color:red">*</span>
                            @Html.TextBoxFor(m => m.TotalSubjects, new { @class = "form-control", @type = "number", @min = "0", style = "max-width: 50px;", required = "required", id = "txtTotalSubject" })

                        </div>
                        
                        <div class="form-group">
                            <input type="submit" name="submit" value="Submit" class="btn btn-success" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>